Repository Project-Namu/namu, pull requests merged in 2023-07, with the labels that each got.

#1 Post Section UI 및 기능 구현 PR 입니다.
  .eslintrc.js
  package-lock.json
  package.json
  src/App.js
  src/Components/Post/carousel.js
  src/Components/Post/carouselItem.js
  src/Components/Post/postDetail.js
  src/Components/Post/requestModal.js
  src/Components/UI/Sidebar.js
  src/Components/UI/button.js
  src/Components/UI/chatSection.js
  src/Components/UI/header.js
  src/Components/UI/listContainer.js
  src/Components/UI/modal.js
  src/Components/UI/postSection.js
  src/Pages/main.js
Labels: fe, feat

#2 Post Section 태그 설정 컴포넌트 관련 PR 입니다.
  src/Components/Post/carousel.js
  src/Components/Tag/editTag.js
  src/Components/Tag/myTagList.js
  src/Components/Tag/searchResultItem.js
  src/Components/UI/searchInput.js
  src/Components/UI/searchResultList.js
  src/Pages/main.js
Labels: fe, feat, design

#3 구글 로그인 및 로그아웃 기능 관련 PR입니다.
  .gitignore
  package-lock.json
  package.json
  src/Components/UI/header.js
  src/Components/header.js
  src/firebase.js
Labels: fe, feat

#4 Search 페이지 관련 PR입니다.
  package-lock.json
  package.json
  src/App.js
  src/Components/Post/carousel.js
  src/Components/Post/postDetail.js
  src/Components/Search/searchItem.js
  src/Components/Search/searchList.js
  src/Components/Tag/editTag.js
  src/Components/Tag/tagItem.js
  src/Components/Tag/tagList.js
  src/Components/UI/Sidebar.js
  src/Components/UI/chatSection.js
  src/Components/UI/listContainer.js
  src/Components/UI/postSection.js
  src/Pages/main.js
  src/Pages/search.js
Labels: fe, feat

#5 Post 작성 페이지 관련 PR 입니다.
  .firebaserc
  firebase.json
  package-lock.json
  package.json
  src/App.js
  src/Components/Post/carousel.js
  src/Components/Post/carouselItem.js
  src/Components/Post/postDetail.js
  src/Components/Post/textEditor.js
  src/Components/Tag/editTag.js
  src/Components/UI/tagInput.js
  src/Pages/main.js
  src/Pages/post.js
  src/firebase.js
  storage.rules
Labels: fe, feat, design

#6 Post Section CSS 리팩토링 및 DB 연결 관련 PR 입니다.
  .eslintrc.js
  src/App.js
  src/Components/Post/carousel.js
  src/Components/Post/carouselItem.js
  src/Components/Post/postDetail.js
  src/Components/Post/requestModal.js
  src/Components/Search/searchItem.js
  src/Components/Tag/editTag.js
  src/Components/Tag/tagItem.js
  src/Components/UI/Sidebar.js
  src/Components/UI/modal.js
  src/Components/UI/searchInput.js
  src/Components/UI/tagInput.js
  src/Pages/main.js
  src/Pages/post.js
  src/Pages/search.js
  src/firebase.js
Labels: fe, be, feat, refactor, design

#7 feat : 로그인 여부 상태 최상단 배치 및 페이지 라우팅 일부 수정
  src/App.js
  src/Components/MyPage/userInfo.js
  src/Components/MyPage/userPostList.js
  src/Components/MyPage/userRequestList.js
  src/Components/MyPage/userTitle.js
  src/Components/UI/TabMenu.js
  src/Components/UI/header.js
  src/MainHome.js
  src/Pages/mypage.js
Labels: fe, feat

#8 마이페이지 배치 변경 및 기본 메뉴틀 구성 관련 PR입니다.
  src/Components/MyPage/userInfo.js
  src/Components/MyPage/userPostList.js
  src/Components/MyPage/userRequestList.js
  src/Components/MyPage/userTitle.js
  src/Components/UI/TabMenu.js
  src/Components/UI/header.js
  src/Pages/mypage.js
Labels: fe, design

#9 postSection DB 연결 및 코드 리팩토링 관련 PR 입니다.
  .eslintrc.js
  package-lock.json
  package.json
  src/App.js
  src/Components/API/Post/fetchPost.js
  src/Components/Post/carousel.js
  src/Components/Post/carouselItem.js
  src/Components/Post/postDetail.js
  src/Components/Post/requestModal.js
  src/Components/Post/textEditor.js
  src/Components/Search/searchItem.js
  src/Components/Search/searchList.js
  src/Components/Tag/editTag.js
  src/Components/Tag/tagItem.js
  src/Components/Tag/tagList.js
  src/Components/UI/Sidebar.js
  src/Components/UI/header.js
  src/Components/UI/modal.js
  src/Components/UI/postSection.js
  src/Components/UI/searchInput.js
  src/Components/UI/tagInput.js
  src/MainHome.js
  src/Pages/createPostPage.js
  src/Pages/editTagPage.js
  src/Pages/main.js
  src/Pages/mainPage.js
  src/Pages/postDetailPage.js
  src/Pages/searchPage.js
  src/Pages/updatePostPage.js
Labels: fe, feat, fix, refactor

#10 로그인 여부 및 로그인 유저 데이터 리코일 적용 관련 PR입니다.
  src/App.js
  src/Components/MyPage/userInfo.js
  src/Components/UI/header.js
  src/MainHome.js
  src/Recoil/atoms.js
  src/index.js
Labels: fe, refactor

#11 react-query 적용(searchPosts 제외) 관련 PR 입니다.
  package-lock.json
  package.json
  src/App.js
  src/Components/API/Post/fetchPost.js
  src/Components/Post/carousel.js
  src/Components/UI/Sidebar.js
  src/Pages/createPostPage.js
  src/Pages/postDetailPage.js
  src/Pages/updatePostPage.js
Labels: fe, feat

#12 신규 유저 DB 저장 관련 PR입니다.
  src/Components/UI/header.js
  src/index.js
Labels: fe, feat

#13 로딩 인디케이터 추가 및 postSection UI 리팩토링 관련 PR 입니다.
  package-lock.json
  package.json
  src/Components/API/Post/fetchPost.js
  src/Components/Post/carousel.js
  src/Components/Post/carouselItem.js
  src/Components/Post/requestModal.js
  src/Components/UI/Sidebar.js
  src/Components/UI/loading.js
  src/Components/UI/postSection.js
  src/Pages/postDetailPage.js
Labels: fe, design

#14 로그인 및 NotFound 페이지 추가 및 관심사 분리 관련 PR입니다.
  src/Components/API/Login/fetchUser.js
  src/Components/UI/header.js
  src/MainHome.js
  src/Pages/loginPage.js
  src/Pages/notFoundPage.js
Labels: fe, feat, refactor

#15 태그 수정 기능 및 게시글 유저 데이터 추가 관련 PR 입니다.
  src/Components/API/Post/fetchPost.js
  src/Components/API/Tag/fetchTag.js
  src/Components/Post/carousel.js
  src/MainHome.js
  src/Pages/createPostPage.js
  src/Pages/editTagPage.js
  src/Pages/mainPage.js
  src/Pages/postDetailPage.js
Labels: fe, feat

#16 요청 전송 기능 구현 관련 PR 입니다.
  src/Components/API/Request/fetchRequest.js
  src/Components/Post/requestModal.js
  src/Pages/postDetailPage.js
Labels: fe, feat

#17 나무 요청 모달 버튼 클릭 error 수정 관련 PR 입니다.
  src/Components/Post/requestModal.js
  src/Pages/postDetailPage.js
Labels: fix

#18 유저의 태그 리스트가 비어있을 시 컴포넌트에 0 출력되는 현상 수정 관련 PR 입니다.
  src/Components/Post/carousel.js
Labels: fix

#19 채팅 컴포넌트 와이어프레임 구성 및 기타 오류 보수
  src/App.js
  src/Components/Chat/chatList.js
  src/Components/Chat/chatRoom.js
  src/Components/Chat/requestList.js
  src/Components/UI/chatSection.js
  src/Components/UI/header.js
  src/MainHome.js
  src/Recoil/atoms.js
Labels: fe, fix, design

#20 나무 요청 전송 시 글쓴이 및 요청자 users 데이터에 요청 데이터 추가 관련 PR 입니다.
  src/Components/API/Request/fetchRequest.js
  src/Components/Post/requestModal.js
  src/Pages/postDetailPage.js
Labels: fe, feat

#21 요청 리스트 모달 연결 및 파이어 스토어 유저 데이터 관련 PR입니다.
  src/Components/Chat/requestList.js
  src/Components/MyPage/userInfo.js
  src/Components/MyPage/userRequestList.js
  src/Components/UI/header.js
  src/Components/UI/requestListModal.js
  src/MainHome.js
  src/Pages/mainPage.js
Labels: fe, feat, design

#22 코드 리팩토링 및 요청 데이터 DB 연결 관련 PR 입니다.
  src/App.js
  src/Components/API/Request/fetchRequest.js
  src/Components/Chat/requestList.js
  src/Components/UI/Sidebar.js
  src/Components/UI/requestListModal.js
  src/MainHome.js
  src/Pages/createPostPage.js
  src/Pages/mainPage.js
  src/Pages/postDetailPage.js
Labels: feat, refactor

#23 채팅방 및 마이페이지 요청 목록 관련 PR입니다.
  package-lock.json
  package.json
  src/App.js
  src/Components/Chat/chatRoom.js
  src/Components/Chat/requestList.js
  src/Components/MyPage/userInfo.js
  src/Components/MyPage/userRequestList.js
  src/Components/UI/requestListModal.js
  src/Pages/mypage.js
Labels: fe, feat, fix

#24 리코일 전역 데이터 새로고침 이슈 및 마이페이지 유저 요청 리스트 기능 구현 관련 PR 입니다.
  .eslintrc.js
  package-lock.json
  package.json
  src/App.js
  src/Components/API/Request/fetchRequest.js
  src/Components/Chat/requestList.js
  src/Components/MyPage/userRequestList.js
  src/Components/Post/carousel.js
  src/Components/Post/carouselItem.js
  src/Components/Post/requestModal.js
  src/Components/Post/textEditor.js
  src/Components/Search/searchItem.js
  src/Components/Tag/tagItem.js
  src/Components/UI/header.js
  src/Components/UI/searchInput.js
  src/Components/UI/tagInput.js
  src/Pages/createPostPage.js
  src/Pages/editTagPage.js
  src/Pages/mypage.js
  src/Pages/postDetailPage.js
  src/Pages/updatePostPage.js
  src/Recoil/atoms.js
Labels: fe, fix

#25 불필요한 useCallback 제거 및 나무 요청 애로사항 관련 PR 입니다.
  src/Components/Post/requestModal.js
  src/Components/UI/searchInput.js
  src/Components/UI/tagInput.js
  src/Pages/createPostPage.js
  src/Pages/postDetailPage.js
  src/Pages/updatePostPage.js
Labels: fix

#26 채팅방 목록 DB 연결 및 채팅방 생성 기능 관련 PR입니다.
  src/Components/API/Chat/fetchChat.js
  src/Components/API/Login/fetchUser.js
  src/Components/Chat/chatList.js
  src/Components/Chat/chatRoom.js
  src/Components/UI/header.js
  src/Components/UI/requestListModal.js
  src/Recoil/atoms.js
Labels: fe, feat

#27 목패 UI 및 기능 구현 관련 PR 입니다.
  package-lock.json
  package.json
  src/Components/API/Login/fetchUser.js
  src/Components/MyPage/userInfo.js
  src/Components/MyPage/userTitle.js
  src/Components/UI/header.js
  src/Recoil/atoms.js
Labels: fe, feat

#28 헬퍼 평가, 채팅 기능 및 마이페이지 기능 일부 관련 PR입니다.
  src/Components/API/Chat/fetchChat.js
  src/Components/API/Post/fetchPost.js
  src/Components/Chat/chatList.js
  src/Components/Chat/chatRoom.js
  src/Components/Chat/pointModal.js
  src/Components/MyPage/userPostList.js
  src/Components/UI/requestListModal.js
Labels: fe, feat

#29 채팅 실시간 데이터 업데이트 기능 및 리액트 쿼리 데이터 fetching delay time으로 인한 에러 해결 관련 PR 입니다.
  src/Components/API/Post/fetchPost.js
  src/Components/Chat/chatList.js
  src/Components/Chat/chatRoom.js
  src/Components/Chat/requestList.js
  src/Components/MyPage/userTitle.js
Labels: feat, fix

#30 목패 취득 및 레벨 변경 기능 관련 PR 입니다.
  src/Components/API/Login/fetchUser.js
  src/Components/MyPage/userPostList.js
  src/Components/MyPage/userTitle.js
  src/Pages/mypage.js
Labels: be, feat

#31 유저 레벨에 따른 유저 아이콘 변경 및 유저 작성글 목록 관련 PR입니다.
  src/Components/MyPage/userInfo.js
  src/Components/MyPage/userPostList.js
  src/Components/UI/header.js
Labels: fe, feat, fix

#32 PointModal 관련 기능 및 Chat 관련 목록에서의 시간 출력 보완 관련 PR입니다.
  package-lock.json
  package.json
  src/Components/API/Chat/fetchChat.js
  src/Components/Chat/chatList.js
  src/Components/Chat/chatRoom.js
  src/Components/Chat/pointModal.js
  src/Components/Chat/requestList.js
Labels: fe, feat, fix

#33 채팅방 이미지 업로드 기능 구현 관련 PR입니다.
  src/Components/API/Chat/fetchChat.js
  src/Components/Chat/chatRoom.js
Labels: fe, feat
